export interface GlossaryTerm {
  id: string;
  term: string;
  fullName: string;
  definition: string;
  formula?: string;
  relatedTerms: string[];
  seenInModules: string[];
}

export const GLOSSARY: GlossaryTerm[] = [
  {
    id: 'rocof',
    term: 'RoCoF',
    fullName: 'Rate of Change of Frequency',
    definition: 'Velocidad de cambio de frecuencia. Mide cuánto cambia la frecuencia de la red por segundo (Hz/s). En el 28-A, el RoCoF fue de -2.2 Hz/s, uno de los más altos registrados en Europa.',
    formula: 'RoCoF = ΔF / Δt (Hz/s)',
    relatedTerms: ['Inercia', 'Estabilidad de frecuencia', 'Sistemas sin inercia'],
    seenInModules: ['inercia-vulnerabilidad', 'grid-following', 'tap-lag'],
  },
  {
    id: 'inercia-sincrona',
    term: 'Inercia Síncrona',
    fullName: 'Synchronous Inertia',
    definition: 'Capacidad natural de los generadores síncronos para resistir cambios de frecuencia. Caracterizada por la constante H (inercia del sistema). A mayor H, mayor resistencia a cambios rápidos.',
    formula: 'H = (M × ω²) / (2 × Pn)',
    relatedTerms: ['Constante H', 'Generadores síncronos', 'RoCoF'],
    seenInModules: ['inercia-vulnerabilidad', 'tres-narrativas'],
  },
  {
    id: 'grid-forming',
    term: 'Grid-Forming (GFM)',
    fullName: 'Grid-Forming Converter',
    definition: 'Inversor que genera tensión activamente, como lo hacen los generadores síncronos. Más estable que Grid-Following pero más complejo. Clave para la transición energética.',
    formula: null,
    relatedTerms: ['Grid-Following', 'IBR', 'Convertidores'],
    seenInModules: ['grid-following', 'tap-lag'],
  },
  {
    id: 'grid-following',
    term: 'Grid-Following (GFL)',
    fullName: 'Grid-Following Converter',
    definition: 'Inversor que se sincroniza con la tensión existente en la red. Más simple pero requiere una red fuerte. Vulnerable a cambios rápidos de frecuencia.',
    formula: null,
    relatedTerms: ['Grid-Forming', 'IBR', 'PLL'],
    seenInModules: ['grid-following', 'tap-lag-explainer'],
  },
  {
    id: 'ufls',
    term: 'UFLS',
    fullName: 'Under Frequency Load Shedding',
    definition: 'Sistema automático que desconecta cargas cuando la frecuencia cae por debajo de umbrales críticos. Último recurso para evitar colapso total de la red.',
    formula: null,
    relatedTerms: ['Protecciones de red', 'Frecuencia', 'Estabilidad'],
    seenInModules: ['tap-lag-explainer', 'inercia-vulnerabilidad'],
  },
  {
    id: 'pll',
    term: 'PLL',
    fullName: 'Phase-Locked Loop',
    definition: 'Circuito de control que sincroniza inversores con la tensión de red. El tiempo de respuesta del PLL es crítico: PLL lento = peor respuesta a eventos de red.',
    formula: null,
    relatedTerms: ['Grid-Following', 'Control de inversores', 'Lag'],
    seenInModules: ['tap-lag-explainer', 'grid-following'],
  },
  {
    id: 'tap-lag',
    term: 'Tap Lag',
    fullName: 'Transformer Tap Changer Lag',
    definition: 'Retraso en la respuesta del cambiador de derivaciones del transformador (automático) al cambiar tensiones. En el 28-A, causó desviaciones de tensión de ±10% que dispararon protecciones.',
    formula: null,
    relatedTerms: ['ULTC', 'Protecciones de tensión', 'Estabilidad de tensión'],
    seenInModules: ['tap-lag-explainer', 'tres-narrativas'],
  },
  {
    id: 'ultc',
    term: 'ULTC',
    fullName: 'Under Load Tap Changer',
    definition: 'Dispositivo que cambia el ratio de transformación del transformador mientras está en operación. Ajusta la tensión pero con retraso que puede causar inestabilidad.',
    formula: null,
    relatedTerms: ['Tap Lag', 'Transformadores', 'Regulación de tensión'],
    seenInModules: ['tap-lag-explainer'],
  },
  {
    id: 'efecto-ferranti',
    term: 'Efecto Ferranti',
    fullName: 'Ferranti Effect',
    definition: 'Aumento de tensión al final de una línea larga sin carga o con poca carga, debido a la capacitancia de la línea. Puede disparar protecciones de sobretensión.',
    formula: null,
    relatedTerms: ['Líneas de transmisión', 'Capacitancia', 'Sobretensión'],
    seenInModules: ['tap-lag-explainer', 'tres-narrativas'],
  },
  {
    id: 'eas',
    term: 'EAS',
    fullName: 'Emergency Control System',
    definition: 'Sistema de control automático que toma decisiones rápidas (milisegundos) para estabilizar la red durante emergencias. En el 28-A, el EAS activó desconexiones de carga.',
    formula: null,
    relatedTerms: ['UFLS', 'Protecciones automáticas', 'Estabilidad'],
    seenInModules: ['tap-lag-explainer', 'inercia-vulnerabilidad'],
  },
  {
    id: 'rms',
    term: 'RMS',
    fullName: 'Root Mean Square',
    definition: 'Valor cuadrático medio. En AC, se usa para expresar voltaje y corriente. 230V RMS es el estándar europeo (pico ≈ 325V).',
    formula: 'RMS = √(1/T ∫₀ᵀ v²(t)dt)',
    relatedTerms: ['Voltaje', 'Corriente', 'Valor pico'],
    seenInModules: ['inercia-vulnerabilidad', 'tap-lag-explainer'],
  },
  {
    id: 'swing-equation',
    term: 'Swing Equation',
    fullName: 'Ecuación de Oscilación',
    definition: 'Ecuación fundamental que describe la dinámica de un generador sincrónico durante transitorios. Base teórica para entender estabilidad transoria.',
    formula: '2H(dω/dt) = Pm - Pe - D(ω - ωn)',
    relatedTerms: ['Inercia', 'Estabilidad transoria', 'Generadores síncronos'],
    seenInModules: ['inercia-vulnerabilidad'],
  },
  {
    id: 'tso',
    term: 'TSO',
    fullName: 'Transmission System Operator',
    definition: 'Operador del Sistema de Transmisión. En España, es REE (Red Eléctrica de España). Responsable de mantener el equilibrio y estabilidad de la red nacional.',
    formula: null,
    relatedTerms: ['REE', 'Sistema eléctrico', 'SCADA'],
    seenInModules: ['tres-narrativas', 'tap-lag-explainer'],
  },
  {
    id: 'dso',
    term: 'DSO',
    fullName: 'Distribution System Operator',
    definition: 'Operador del Sistema de Distribución. En España, Endesa, Iberdrola y otros. Responsables de la red local hasta los consumidores.',
    formula: null,
    relatedTerms: ['TSO', 'Distribución eléctrica', 'Redes locales'],
    seenInModules: ['tres-narrativas'],
  },
  {
    id: 'entso-e',
    term: 'ENTSO-e',
    fullName: 'European Network of Transmission System Operators for Electricity',
    definition: 'Asociación europea de operadores de sistemas de transmisión. Coordina estándares de seguridad y estabilidad en toda Europa. En el 28-A, fue parte de la investigación.',
    formula: null,
    relatedTerms: ['TSO', 'Regulación europea', 'Códigos de red'],
    seenInModules: ['tres-narrativas'],
  },
  {
    id: 'hvdc',
    term: 'HVDC',
    fullName: 'High Voltage Direct Current',
    definition: 'Transmisión de corriente continua de alto voltaje. Más eficiente para largas distancias que AC, y ayuda a desacoplar sistemas débiles. Falta de inercia es un reto.',
    formula: null,
    relatedTerms: ['Transmisión', 'Convertidores', 'Grid-Forming'],
    seenInModules: ['grid-following', 'tap-lag-explainer'],
  },
  {
    id: 'statcom',
    term: 'STATCOM',
    fullName: 'Static Synchronous Compensator',
    definition: 'Dispositivo electrónico que proporciona soporte reactivo dinámico (capacitancia/inductancia variable) a la red. Ayuda a estabilizar tensión en tiempos de respuesta muy rápidos (milisegundos).',
    formula: null,
    relatedTerms: ['Grid-Forming', 'Soporte reactivo', 'Estabilidad de tensión'],
    seenInModules: ['tap-lag-explainer', 'grid-following'],
  },
  {
    id: 'ibr',
    term: 'IBR',
    fullName: 'Inverter-Based Resource',
    definition: 'Recursos generadores basados en inversores: paneles solares, turbinas eólicas con electrónica de potencia. Caracter: sin inercia natural, respuesta controlada por software.',
    formula: null,
    relatedTerms: ['Grid-Following', 'Grid-Forming', 'Energías renovables'],
    seenInModules: ['inercia-vulnerabilidad', 'grid-following', 'tap-lag-explainer'],
  },
  {
    id: 'scada',
    term: 'SCADA',
    fullName: 'Supervisory Control and Data Acquisition',
    definition: 'Sistema que monitorea y controla la red eléctrica en tiempo real. REE usa SCADA para observar frecuencia, tensiones, flujos y activar protecciones automáticas.',
    formula: null,
    relatedTerms: ['TSO', 'REE', 'Control automático'],
    seenInModules: ['tres-narrativas', 'inercia-vulnerabilidad'],
  },
  {
    id: 'redes-debiles',
    term: 'Redes Débiles',
    fullName: 'Weak Grids',
    definition: 'Redes con baja capacidad de cortocircuito y/o sin generadores síncronos (mucha renovable). Vulnerable a cambios rápidos de frecuencia y voltaje. Requiere soporte electrónico.',
    formula: null,
    relatedTerms: ['IBR', 'Inercia', 'Grid-Following'],
    seenInModules: ['inercia-vulnerabilidad', 'tap-lag-explainer'],
  },
  {
    id: 'constante-h',
    term: 'Constante H',
    fullName: 'Inertia Constant',
    definition: 'Parámetro que cuantifica la inercia de un sistema (en segundos). H = Energía cinética / Potencia nominal. En 2023, H español ≈ 4-5s. En 2000s, era ≈ 10s.',
    formula: 'H [s] = (M × ω²) / (2 × Pn)',
    relatedTerms: ['Inercia Síncrona', 'RoCoF', 'Swing Equation'],
    seenInModules: ['inercia-vulnerabilidad'],
  },
  {
    id: 'frecuencia-nominal',
    term: 'Frecuencia Nominal',
    fullName: 'Nominal Frequency',
    definition: 'Frecuencia de referencia de la red: 50 Hz en Europa. Debe mantenerse ±0.2 Hz bajo operación normal. En el 28-A cayó a 47.5 Hz en 9 segundos.',
    formula: 'f = 50 Hz ± 0.2 Hz (normal)',
    relatedTerms: ['RoCoF', 'Estabilidad de frecuencia', 'Protecciones'],
    seenInModules: ['inercia-vulnerabilidad', 'tres-narrativas', 'tap-lag-explainer'],
  },
];
